######################################################################
# Automatically generated by qmake (3.0) Wed May 28 22:10:01 2014
######################################################################

TEMPLATE = app
TARGET = Graph
INCLUDEPATH += .

# Input
HEADERS += Terminal.h
SOURCES += main.cpp Terminal.cpp

QT += widgets
